# 整个流程的名字
name: Version

on:
  push:
    branches:
      - release/**

# 默认shell
defaults:
  run:
    shell: bash

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # 设置 pnpm。指定版本7.0，不然会报错
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.x

      # 设置 Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      # 安装依赖
      - name: Install dependencies
        run: pnpm install
      # 创建pr
      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
